spring:
  application:
    name: server-atleta
  profiles:
    active: dev

# Common configuration for all profiles
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,flyway,prometheus
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      percentiles:
        "[http.server.requests]": 0.5, 0.95, 0.99
  health:
    db:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

features:
  mvp-xp-bonus-enabled: ${MVP_XP_BONUS_ENABLED:true}
