package com.atleta.demo.enums;

public enum NotificationType {
    SOLICITUD_AMISTAD,
    RESPUESTA_AMISTAD,
    INVITACION_EQUIPO,
    RESPUESTA_INVITACION_EQUIPO,
    INVITACION_PARTIDO,
    RESPUESTA_INVITACION_PARTIDO,
    FORMULARIO_INCOMPLETO
}
