package com.atleta.demo.entity;

import net.jqwik.api.*;
import org.junit.jupiter.api.DisplayName;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Property-based tests for Athlete entity uniqueness and validation.
 * Feature: api-foundation, Property 1: Unicidad de atletas
 * Validates: Requirements 1.1, 1.2
 */
class AthletePropertyTest {

    @Property(tries = 10)
    @DisplayName("Athlete UUID should be null before persistence and unique across instances")
    void athleteUuidShouldBeNullBeforePersistence(@ForAll String email, @ForAll String passwordHash, @ForAll String nombre) {
        // Property: For any valid athlete data, UUID should be null before persistence
        Athlete athlete = new Athlete(email, passwordHash, nombre);
        
        // UUID should be null before persistence (will be generated by database)
        assertThat(athlete.getAtletaUuid()).isNull();
        
        // Basic field validation
        assertThat(athlete.getEmail()).isEqualTo(email);
        assertThat(athlete.getPasswordHash()).isEqualTo(passwordHash);
        assertThat(athlete.getNombre()).isEqualTo(nombre);
        assertThat(athlete.getCreatedAt()).isNull(); // Will be set by @CreationTimestamp
    }

    @Property(tries = 10)
    @DisplayName("Athletes with different emails should be considered different entities")
    void athletesWithDifferentEmailsShouldBeDifferent(@ForAll String email1, @ForAll String email2) {
        Assume.that(!email1.equals(email2));
        
        // Property: For any two athletes with different emails, they should be different entities
        Athlete athlete1 = new Athlete(email1, "hash1", "name1");
        Athlete athlete2 = new Athlete(email2, "hash2", "name2");
        
        // Before persistence, both should have null UUIDs
        assertThat(athlete1.getAtletaUuid()).isNull();
        assertThat(athlete2.getAtletaUuid()).isNull();
        
        // They should not be equal (since UUIDs are null, comparison is based on class)
        assertThat(athlete1).isNotEqualTo(athlete2);
        assertThat(athlete1.getEmail()).isNotEqualTo(athlete2.getEmail());
    }

    @Property(tries = 10)
    @DisplayName("Athletes with same UUID should be equal")
    void athletesWithSameUuidShouldBeEqual(@ForAll String email) {
        // Property: For any athlete data, two athletes with same UUID should be equal
        Athlete athlete1 = new Athlete(email, "hash1", "name1");
        Athlete athlete2 = new Athlete(email + ".different", "different-hash", "Different Name");
        
        // Set same UUID for both
        UUID sameUuid = UUID.randomUUID();
        athlete1.setAtletaUuid(sameUuid);
        athlete2.setAtletaUuid(sameUuid);
        
        // They should be equal based on UUID
        assertThat(athlete1).isEqualTo(athlete2);
        assertThat(athlete1.hashCode()).isEqualTo(athlete2.hashCode());
    }

    @Property(tries = 10)
    @DisplayName("Simple validation test")
    void simpleValidationTest(@ForAll String email) {
        // Property: For any athlete data, validation should work
        Athlete athlete = new Athlete(email, "hash", "name");
        
        // Basic assertions
        assertThat(athlete.getEmail()).isEqualTo(email);
        assertThat(athlete.getPasswordHash()).isEqualTo("hash");
        assertThat(athlete.getNombre()).isEqualTo("name");
    }
}