-- PostgreSQL schema for Atleta
-- Version: V001

-- Tabla de atletas
CREATE TABLE athletes (
    atleta_uuid UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Tabla de posiciones
CREATE TABLE positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Tabla de perfiles de jugador
CREATE TABLE player_profiles (
    atleta_uuid UUID PRIMARY KEY,
    alias VARCHAR(50),
    trust_score INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_player_profiles_athlete
        FOREIGN KEY (atleta_uuid) REFERENCES athletes(atleta_uuid)
);

-- Tabla de equipos
CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    logo_url VARCHAR(500),
    anio_fundacion INTEGER,
    creador_user_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_teams_creator
        FOREIGN KEY (creador_user_id) REFERENCES player_profiles(atleta_uuid)
);

-- Tabla de posiciones de jugador
CREATE TABLE player_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id UUID NOT NULL,
    position_id BIGINT NOT NULL,
    prioridad INTEGER NOT NULL CHECK (prioridad IN (1, 2, 3)),
    xp INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_player_positions_player FOREIGN KEY (player_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT fk_player_positions_position FOREIGN KEY (position_id) REFERENCES positions(id),
    UNIQUE (player_id, position_id),
    UNIQUE (player_id, prioridad)
);

-- Tabla de partidos
CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modalidad VARCHAR(20) NOT NULL CHECK (modalidad IN ('CINCO_VS_CINCO', 'SEIS_VS_SEIS', 'SIETE_VS_SIETE')),
    fecha_hora_programada TIMESTAMP NOT NULL,
    latitud DECIMAL(10,8) CHECK (latitud BETWEEN -90 AND 90),
    longitud DECIMAL(11,8) CHECK (longitud BETWEEN -180 AND 180),
    cuota DECIMAL(10,2) CHECK (cuota >= 0),
    creador_user_id UUID NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'CREADO' CHECK (estado IN ('CREADO', 'INICIADO', 'FINALIZADO', 'INVALIDO')),
    started_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_matches_creator FOREIGN KEY (creador_user_id) REFERENCES player_profiles(atleta_uuid)
);

-- Tabla de miembros de equipo
CREATE TABLE team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    rol VARCHAR(20) NOT NULL DEFAULT 'JUGADOR' CHECK (rol IN ('JUGADOR', 'CAPITAN', 'DT')),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_team_members_team FOREIGN KEY (team_id) REFERENCES teams(id),
    CONSTRAINT fk_team_members_user FOREIGN KEY (user_id) REFERENCES player_profiles(atleta_uuid)
);

-- Tabla de equipos en partidos
CREATE TABLE match_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    es_local BOOLEAN NOT NULL,
    goles INTEGER NOT NULL DEFAULT 0 CHECK (goles >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_match_teams_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_match_teams_team FOREIGN KEY (team_id) REFERENCES teams(id),
    UNIQUE (match_id, team_id),
    UNIQUE (match_id, es_local)
);

-- Tabla de jugadores en partidos
CREATE TABLE match_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    position_id BIGINT NOT NULL,
    rol VARCHAR(20) NOT NULL CHECK (rol IN ('JUGADOR', 'CAPITAN', 'DT')),
    confirmado BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_match_players_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_match_players_team FOREIGN KEY (team_id) REFERENCES teams(id),
    CONSTRAINT fk_match_players_user FOREIGN KEY (user_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT fk_match_players_position FOREIGN KEY (position_id) REFERENCES positions(id),
    UNIQUE (match_id, user_id),
    UNIQUE (match_id, team_id, rol)
);

-- Tabla de eventos
CREATE TABLE match_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    tipo_evento VARCHAR(20) NOT NULL CHECK (tipo_evento IN ('GOL', 'ASISTENCIA')),
    player_id UUID NOT NULL,
    team_id BIGINT NOT NULL,
    assist_player_id UUID,
    registered_by_id UUID NOT NULL,
    confirmed_by_home BOOLEAN NOT NULL DEFAULT FALSE,
    confirmed_by_away BOOLEAN NOT NULL DEFAULT FALSE,
    registered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_match_events_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_match_events_player FOREIGN KEY (player_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT fk_match_events_team FOREIGN KEY (team_id) REFERENCES teams(id),
    CONSTRAINT fk_match_events_assist FOREIGN KEY (assist_player_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT fk_match_events_registered_by FOREIGN KEY (registered_by_id) REFERENCES player_profiles(atleta_uuid)
);

-- Tabla de historial
CREATE TABLE player_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    team_id BIGINT NOT NULL,
    position_id BIGINT NOT NULL,
    goles INTEGER NOT NULL DEFAULT 0 CHECK (goles >= 0),
    asistencias INTEGER NOT NULL DEFAULT 0 CHECK (asistencias >= 0),
    resultado VARCHAR(20) NOT NULL CHECK (resultado IN ('VICTORIA', 'EMPATE', 'DERROTA')),
    xp_ganada INTEGER NOT NULL DEFAULT 0 CHECK (xp_ganada >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_player_history_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_player_history_user FOREIGN KEY (user_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT fk_player_history_team FOREIGN KEY (team_id) REFERENCES teams(id),
    CONSTRAINT fk_player_history_position FOREIGN KEY (position_id) REFERENCES positions(id)
);

-- Tabla de logs de confianza
CREATE TABLE trust_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    match_id BIGINT,
    cambio INTEGER NOT NULL,
    trust_score_anterior INTEGER NOT NULL,
    trust_score_nuevo INTEGER NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    changed_by_id UUID,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_trust_logs_user FOREIGN KEY (user_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT fk_trust_logs_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_trust_logs_changed_by FOREIGN KEY (changed_by_id) REFERENCES player_profiles(atleta_uuid)
);

-- Tabla de estadísticas de equipos
CREATE TABLE team_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    partidos_jugados INTEGER NOT NULL DEFAULT 0 CHECK (partidos_jugados >= 0),
    partidos_ganados INTEGER NOT NULL DEFAULT 0 CHECK (partidos_ganados >= 0),
    partidos_empatados INTEGER NOT NULL DEFAULT 0 CHECK (partidos_empatados >= 0),
    partidos_perdidos INTEGER NOT NULL DEFAULT 0 CHECK (partidos_perdidos >= 0),
    goles_favor INTEGER NOT NULL DEFAULT 0 CHECK (goles_favor >= 0),
    goles_contra INTEGER NOT NULL DEFAULT 0 CHECK (goles_contra >= 0),
    puntos INTEGER NOT NULL DEFAULT 0 CHECK (puntos >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_team_stats_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

-- Datos base
INSERT INTO positions (nombre) VALUES
('Portero'),
('Defensa'),
('Mediocampo'),
('Delantero'),
('Lateral Derecho'),
('Lateral Izquierdo');
