-- Crear tabla player_ratings para el Sistema de Calificación de Jugadores
-- Versión: V003
-- Descripción: Tabla para almacenar calificaciones actuales de jugadores por rol y prioridad

-- Tabla de calificaciones de jugadores
CREATE TABLE player_ratings (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_profile_id     UUID NOT NULL,
    role_type             VARCHAR(20) NOT NULL CHECK (role_type IN ('ATAQUE', 'DEFENSA', 'MEDIOCAMPO', 'CARRILERO', 'ARQUERO', 'DT')),
    priority_level        VARCHAR(20) NOT NULL CHECK (priority_level IN ('PRINCIPAL', 'SECUNDARIA', 'TERCIARIA')),
    current_rating        DECIMAL(5,2) NOT NULL CHECK (current_rating >= 0.00 AND current_rating <= 999.99),
    matches_played        INTEGER NOT NULL DEFAULT 0 CHECK (matches_played >= 0),
    last_updated          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP,
    version               BIGINT NOT NULL DEFAULT 0,
    
    -- Foreign key constraints
    FOREIGN KEY (player_profile_id) REFERENCES player_profiles(atleta_uuid),
    
    -- Unique constraint to ensure one rating per player-role-priority combination
    CONSTRAINT uk_player_role_priority UNIQUE (player_profile_id, role_type, priority_level)
);

-- Índices para optimizar consultas frecuentes
CREATE INDEX idx_player_ratings_player_id ON player_ratings(player_profile_id);
CREATE INDEX idx_player_ratings_role_type ON player_ratings(role_type);
CREATE INDEX idx_player_ratings_priority_level ON player_ratings(priority_level);
CREATE INDEX idx_player_ratings_current_rating ON player_ratings(current_rating);
CREATE INDEX idx_player_ratings_last_updated ON player_ratings(last_updated);

-- Índice compuesto para consultas por jugador y rol
CREATE INDEX idx_player_ratings_player_role ON player_ratings(player_profile_id, role_type);

-- Índice compuesto para consultas por jugador y prioridad
CREATE INDEX idx_player_ratings_player_priority ON player_ratings(player_profile_id, priority_level);