-- Crear tabla rating_history para el Sistema de Calificación de Jugadores
-- Versión: V004
-- Descripción: Tabla para almacenar historial de cambios de calificación con detalles de cálculo

-- Tabla de historial de calificaciones
CREATE TABLE rating_history (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_rating_id            BIGINT NOT NULL,
    match_id                    BIGINT NOT NULL,
    previous_rating             DECIMAL(5,2) NOT NULL CHECK (previous_rating >= 0.00 AND previous_rating <= 999.99),
    new_rating                  DECIMAL(5,2) NOT NULL CHECK (new_rating >= 0.00 AND new_rating <= 999.99),
    rating_delta                DECIMAL(6,2) NOT NULL CHECK (rating_delta >= -999.99 AND rating_delta <= 999.99),
    goals_scored                INTEGER NOT NULL CHECK (goals_scored >= 0),
    assists_made                INTEGER NOT NULL CHECK (assists_made >= 0),
    goals_conceded              INTEGER CHECK (goals_conceded >= 0),
    was_mvp                     BOOLEAN NOT NULL,
    match_result                VARCHAR(20) NOT NULL CHECK (match_result IN ('GANADO', 'EMPATE', 'PERDIDO')),
    rotative_goalkeeper_mode    BOOLEAN NOT NULL DEFAULT FALSE,
    result_points               DECIMAL(4,2) CHECK (result_points >= -99.99 AND result_points <= 99.99),
    weighted_goal_points        DECIMAL(4,2) CHECK (weighted_goal_points >= 0.00 AND weighted_goal_points <= 99.99),
    weighted_assist_points      DECIMAL(4,2) CHECK (weighted_assist_points >= 0.00 AND weighted_assist_points <= 99.99),
    defensive_bonus             DECIMAL(4,2) CHECK (defensive_bonus >= 0.00 AND defensive_bonus <= 99.99),
    mvp_bonus                   DECIMAL(4,2) CHECK (mvp_bonus >= 0.00 AND mvp_bonus <= 99.99),
    priority_multiplier         DECIMAL(3,2) CHECK (priority_multiplier >= 0.00 AND priority_multiplier <= 9.99),
    created_at                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP,
    version                     BIGINT NOT NULL DEFAULT 0,
    
    -- Foreign key constraints
    FOREIGN KEY (player_rating_id) REFERENCES player_ratings(id),
    FOREIGN KEY (match_id) REFERENCES matches(id)
);

-- Índices para optimizar consultas frecuentes
CREATE INDEX idx_rating_history_player_rating_id ON rating_history(player_rating_id);
CREATE INDEX idx_rating_history_match_id ON rating_history(match_id);
CREATE INDEX idx_rating_history_match_result ON rating_history(match_result);
CREATE INDEX idx_rating_history_was_mvp ON rating_history(was_mvp);
CREATE INDEX idx_rating_history_rotative_mode ON rating_history(rotative_goalkeeper_mode);
CREATE INDEX idx_rating_history_created_at ON rating_history(created_at);

-- Índice compuesto para consultas de historial por jugador y fecha
CREATE INDEX idx_rating_history_player_date ON rating_history(player_rating_id, created_at);

-- Índice compuesto para consultas de historial por partido y resultado
CREATE INDEX idx_rating_history_match_result_combo ON rating_history(match_id, match_result);

-- Índice compuesto para análisis de rendimiento MVP
CREATE INDEX idx_rating_history_mvp_analysis ON rating_history(was_mvp, match_result, created_at);