CREATE TABLE field_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    ciudad VARCHAR(120) NOT NULL,
    latitud DECIMAL(10,8) NOT NULL CHECK (latitud BETWEEN -90 AND 90),
    longitud DECIMAL(11,8) NOT NULL CHECK (longitud BETWEEN -180 AND 180),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_field_locations_nombre_ciudad UNIQUE (nombre, ciudad)
);

CREATE INDEX idx_field_locations_ciudad ON field_locations(ciudad);
CREATE INDEX idx_field_locations_activo ON field_locations(activo);
