CREATE TABLE friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id UUID NOT NULL,
    target_user_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDIENTE', 'ACEPTADA', 'RECHAZADA', 'CANCELADA')),
    responded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_friendships_requester FOREIGN KEY (requester_user_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT fk_friendships_target FOREIGN KEY (target_user_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT ck_friendships_distinct_users CHECK (requester_user_id <> target_user_id)
);

CREATE UNIQUE INDEX uq_friendships_pair ON friendships (requester_user_id, target_user_id);
CREATE INDEX idx_friendships_target_status ON friendships (target_user_id, status);
CREATE INDEX idx_friendships_requester_status ON friendships (requester_user_id, status);

CREATE TABLE team_invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    requester_user_id UUID NOT NULL,
    target_user_id UUID NOT NULL,
    message VARCHAR(255),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDIENTE', 'ACEPTADA', 'RECHAZADA', 'CANCELADA')),
    responded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_team_invites_team FOREIGN KEY (team_id) REFERENCES teams(id),
    CONSTRAINT fk_team_invites_requester FOREIGN KEY (requester_user_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT fk_team_invites_target FOREIGN KEY (target_user_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT ck_team_invites_distinct_users CHECK (requester_user_id <> target_user_id)
);

CREATE INDEX idx_team_invites_target_status ON team_invites (target_user_id, status);
CREATE INDEX idx_team_invites_team_status ON team_invites (team_id, status);

CREATE TABLE match_invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    team_id BIGINT,
    requester_user_id UUID NOT NULL,
    target_user_id UUID NOT NULL,
    message VARCHAR(255),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDIENTE', 'ACEPTADA', 'RECHAZADA', 'CANCELADA')),
    responded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_match_invites_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_match_invites_team FOREIGN KEY (team_id) REFERENCES teams(id),
    CONSTRAINT fk_match_invites_requester FOREIGN KEY (requester_user_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT fk_match_invites_target FOREIGN KEY (target_user_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT ck_match_invites_distinct_users CHECK (requester_user_id <> target_user_id)
);

CREATE INDEX idx_match_invites_target_status ON match_invites (target_user_id, status);
CREATE INDEX idx_match_invites_match_status ON match_invites (match_id, status);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id UUID NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(120) NOT NULL,
    message VARCHAR(400) NOT NULL,
    context_type VARCHAR(50),
    context_id BIGINT,
    payload_json TEXT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_user_id) REFERENCES player_profiles(atleta_uuid)
);

CREATE INDEX idx_notifications_recipient_read_created ON notifications (recipient_user_id, is_read, created_at DESC);
