-- MVP voting foundation
-- Adds MVP vote table + match-level MVP metadata

ALTER TABLE matches
    ADD COLUMN mvp_voting_closed_at TIMESTAMP;

ALTER TABLE matches
    ADD COLUMN mvp_user_id UUID;

ALTER TABLE matches
    ADD CONSTRAINT fk_matches_mvp_user
        FOREIGN KEY (mvp_user_id) REFERENCES player_profiles(atleta_uuid);

CREATE INDEX idx_matches_mvp_user
    ON matches (mvp_user_id);

CREATE INDEX idx_matches_mvp_voting_closed_at
    ON matches (mvp_voting_closed_at);

CREATE TABLE match_mvp_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    voter_user_id UUID NOT NULL,
    voted_user_id UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_match_mvp_votes_match
        FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_match_mvp_votes_voter
        FOREIGN KEY (voter_user_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT fk_match_mvp_votes_voted
        FOREIGN KEY (voted_user_id) REFERENCES player_profiles(atleta_uuid)
);

ALTER TABLE match_mvp_votes
    ADD CONSTRAINT uk_match_mvp_votes_match_voter
        UNIQUE (match_id, voter_user_id);

CREATE INDEX idx_match_mvp_votes_match
    ON match_mvp_votes (match_id);

CREATE INDEX idx_match_mvp_votes_voted_user
    ON match_mvp_votes (voted_user_id);
