CREATE TABLE push_notification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id UUID NOT NULL,
    token VARCHAR(512) NOT NULL,
    platform VARCHAR(32) NOT NULL,
    device_id VARCHAR(191),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_push_notification_tokens_recipient
        FOREIGN KEY (recipient_user_id) REFERENCES player_profiles(atleta_uuid),
    CONSTRAINT uq_push_notification_tokens_token UNIQUE (token)
);

CREATE INDEX idx_push_notification_tokens_recipient_active_seen
    ON push_notification_tokens (recipient_user_id, is_active, last_seen_at DESC);

CREATE INDEX idx_push_notification_tokens_recipient_device
    ON push_notification_tokens (recipient_user_id, device_id);
